name: "🎟️ Request Hackathon Invite"
description: "Click here to get an invite to the BCX26 GitHub Organization."
title: "Invite: @{{github.actor}}"
labels: ["invite-request"]
body:
  - type: markdown
    attributes:
      value: |
        ## Welcome to BCX26! 🚀
        Check the box below and click the green **Submit new issue** button to automatically receive your invitation to the Bosch-Connected-Experience-26 GitHub Organization.
  - type: checkboxes
    id: confirm
    attributes:
      label: "Confirmation"
      options:
        - label: "Yes, please send me an invite to the organization!"
          required: true
