name: "🎟️ Request Hackathon Invite"
description: "Click here to get an invite to the BCX26 GitHub Organization."
title: "Invite: @{{ github.actor }}"
labels: ["invite-request"]
body:
  - type: markdown
    attributes:
      value: |
        ## Welcome to BCX26! 🚀
        Click the green **Submit new issue** button below to automatically receive your invitation to the Bosch-Connected-Experience-26 GitHub Organization.
